jobs:
    run-tests:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          python-version:
            - "3.10"
            - "3.11"
            - "3.12-dev"
      name: Test      